// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/memories/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/memories/delete/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/memories/:id?" | "/memories/delete/:id";
  };
  "routes/memories.tsx": {
    id: "routes/memories";
    page: "/memories/:id?";
  };
  "routes/memories.delete.tsx": {
    id: "routes/memories.delete";
    page: "/memories/delete/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/memories": typeof import("./app/routes/memories.tsx");
  "routes/memories.delete": typeof import("./app/routes/memories.delete.tsx");
};